### ISSUE TITLE
 Issue to execute in Google crome Browser.

### ISSUE THREAD

**Issue by rohitmishra209** [quentinneyraud/jekyll-starter-kit#10]
Hi,
After clone to your project i executed it in crome but i am facing following issue.It happens in every project of barba js, Can you please suggest me the solution.

=>barba.min.js:1 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///pages/portafolio' cannot be created in a document with origin 'null' and URL 'file:///home/rohit/Training/Barbajs/PageTransitions/index.html'.

But it execute properly in mozilla firefox Browser.

**Comment by quentinneyraud** [comment]
Hi,

Did you run `npm run dev` and go to `localhost:4000` ?

It seems to be a cross origin issue when you access to project with `file://` urls.   
See [pushState documentation](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method).
